repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pylint
        name: Pylint
        entry: pylint
        language: system
        types: [ python ]